create database sql_1sst_project;
use sql_1sst_project;
select * from sales;
/*🏢 Company-Style SQL Questions
🟢 Round 1 — Business Understanding
Q1. Management wants to know the total number of orders received.
Q2. How many unique cities are generating orders?
Q3. Management wants to know the total revenue generated.
Q4. What is the average order sales value?
Q5. Find the highest-value order.
Q6. Find the lowest-value order.*/
select count(order_id) as total_orders from sales ;
select distinct city from sales ;
select sum(sales) as total_revenue from sales;
select avg(sales) as avg_order_value from sales ;
select max(sales) as max_value from sales ;
select min(sales) as min_value from sales ;

/*🟡 Round 2 — Sales Performance
Q7. Management wants total sales by product category.
Q8. Which product category generated the highest total sales?
Q9. Find the total quantity sold for each product.
Q10. Which products sold more than 15 units in total?
Q11. Find the average sales amount for each customer segment.
Q12. Which customer segments generated more than ₹1 lakh total sales?
Q13. Find city-wise total sales.
Q14. Which cities generated more than ₹2 lakh sales?*/
select category ,sum(sales) as total_sales from sales group by category ;
select category ,sum(sales) as highest_sales from sales group by category order by sum(sales) desc ;
select product,sum(quantity) as total_qunty from sales group by product;
select product,sum(quantity) as more_then_15_u from sales group by product having sum(quantity) > 15;
select customer_segment ,avg(sales) as avg_sale_amount from sales group by customer_segment ;
select customer_segment ,sum(sales) as more_then_1l from sales group by customer_segment having sum(sales) > 100000 ;
select city,sum(sales) as total_sales from sales group by city;
select city,sum(sales) as total_sales from sales group by city having sum(sales) > 200000 ;

/*🔵 Round 3 — Profit Analysis
Q15. What is the total profit generated by the company?
Q16. Find total profit by product category.
Q17. Which category generated the highest profit?
Q18. Find the average profit per order.
Q19. Find products where the average profit is greater than ₹2,000.
Q20. Find cities where total profit is greater than ₹30,000.*/
select sum(profit) as total_profit from sales ;
select category,sum(profit) as total_profit from sales group by category ;
select category,sum(profit) as total_profit from sales group by category order by total_profit desc limit 1 ;
select avg(profit) as avg_profit from sales;
select product,avg(profit) as avg_profit from sales group by product having avg_profit > 2000  ;
select city,sum(profit) as total_profit from sales group by city having total_profit > 30000;

/*🟠 Round 4 — Customer & Order Analysis
Q21. How many orders came from each customer segment?
Q22. Which customer segment placed the highest number of orders?
Q23. Find the number of orders for each payment mode.
Q24. Which payment mode was used for the highest number of orders?
Q25. Find the total sales generated through UPI.
Q26. Find all orders where:
Sales > ₹20,000
AND order status = Delivered
Q27. Find all orders where:
discount is greater than 15%
OR profit is greater than ₹10,000 */

select customer_segment,count(order_id) as total_orders from sales group by customer_segment;
select customer_segment,count(order_id) as total_orders from sales group by customer_segment order by total_orders desc limit 1 ;
select payment_mode , count(order_id) as total_order from sales group by payment_mode ;
select payment_mode , count(order_id) as total_order from sales group by payment_mode order by total_order desc limit 1 ;
select  sum(sales) as total_sales from sales where  payment_mode = 'upi' ;
select * from sales where sales > 20000 and order_status = 'delivered' ;
select * from sales where discount_pct > 15 or profit > 10000 ;

/*🔴 Round 5 — Management-Level Questions
Q28. Management wants the Top 5 products by total sales.
Q29. Find the Top 5 highest-profit orders.
Q30. Find the Top 3 cities by total sales.
Q31. Find categories having:
total sales > ₹2 lakh
AND average profit > ₹2,000
Q32. Find the average sales and total profit for each customer segment, but show only segments where total profit is greater than ₹20,000.
Q33. Find the number of delivered, cancelled and returned orders.
Q34. What percentage-style business insight can you derive from order statuses?
(SQL me abhi percentage calculation optional rakhenge.)*/

select product , sum(sales) as total_sales from sales group by product order by total_sales desc limit 5 ;
select order_id,sum(profit) as total_profit from sales group by order_id order by total_profit desc limit 5 ;
select city,sum(sales) as total_sale from sales group by city order by total_sale desc limit 3;
select category,sum(sales) as total_sale , avg(profit) as avg_profit from sales group by category having total_sale > 200000 and avg_profit > 2000;
select customer_segment,avg(sales) as avg_sale , sum(profit) as total_profit from sales group by customer_segment having total_profit > 20000;
select order_status,count(order_id) as total_orders from sales group by order_status order by total_orders desc ;
